services:
  server:
    container_name: ost-autovpc-server
    image: 497217256558.dkr.ecr.ap-northeast-1.amazonaws.com/ost_server:latest
    expose:
      - "3000:3000"

  proxy:
    container_name: ost-autovpc-proxy
    image: 497217256558.dkr.ecr.ap-northeast-1.amazonaws.com/ost_proxy:latest
    ports:
      - "80:80"