version: '3'

services:
  ost-backend:
    container_name: ost-backend-app
    image: ost-backend-app:latest
    restart: always
    networks:
      - ost-backend
    environment:
      - ENV=test
      - TZ=Asia/Toyko
  proxy:
    container_name: ost-nginx
    image: ost-nginx:latest
    restart: always
    networks:
      - ost-backend
    ports:
      - 3000:80


networks:
  ost-backend:
    external: true