version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:497217256558:task-definition/ost-ob-td:5"
        LoadBalancerInfo:
          ContainerName: "ost-nginx"
          ContainerPort: 80